export const ENDPOINTS = {
  AUTH: {
    REGISTER: '/api/v1/auth/register',
    LOGIN: '/api/v1/auth/login',
    LOGOUT: '/api/v1/auth/logout',
    PROFILE: '/api/v1/auth/profile',
    UPDATE: '/api/v1/auth/profile',
    REFRESH_TOKEN: '/api/v1/auth/refresh-token',
    VERIFY_EMAIL:  `/api/v1/auth/verify-email`,
    REQUEST_PASSWORD_RESET: '/api/v1/auth/request-password-reset',
    UPDATE_PASSWORD:  '/api/v1/auth/password',
    FORGOT_PASSWORD:  '/api/v1/auth/forgot-password',
    RESET_PASSWORD:   '/api/v1/auth/reset-password',
    // RESET_PASSWORD: (token: string) => `api/v1/auth/reset-password/${token}`,
  },
  PETS: {
    GET: '/api/v1/pets',
    SEARCH: '/api/v1/pets/search',
    CATEGORIES: '/api/v1/pets/categories',
    GET_ONE: (id: string) => `/api/v1/pets/${id}`,
    FAVORITE: (id: string) => `/api/v1/pets/${id}/favorite`,
    UPDATE: (id: string) => `/api/v1/pets/${id}`,
    DELETE: (id: string) => `/api/v1/pets/${id}`,
    BY_STATUS:  (status: string)  => `/api/v1/pets/status/${status}`,
    BY_SPECIES: (species: string) => `/api/v1/pets/species/${species}`,
    BY_BREED:   (breed: string)   => `/api/v1/pets/breed/${breed}`,
    BY_AGE:     (age: string)     => `/api/v1/pets/age/${age}`,
  },
  AI: {
    MATCH: '/api/v1/ai/match',
    ANALYZE: '/api/v1/ai/analyze-compatibility',
    RECOMMENDATIONS: (userId: string) => `/api/v1/ai/recommendations/${userId}`,
    CHAT: '/api/v1/ai/chat',
    CHAT_HISTORY: '/api/v1/ai/chat-history',
    GENERATE_DESCRIPTION: '/api/v1/ai/generate-description',
  },
  ADMIN: {
    BLOGS: {
      GET: '/api/v1/admin/blogs',
      GET_ONE: (id: string) => `/api/v1/admin/blogs/${id}`,
      CREATE: '/api/v1/admin/blogs',
      UPDATE: (id: string): string => `/api/v1/admin/blogs/${id}`,
      DELETE: (id: string): string => `/api/v1/admin/blogs/${id}`,
    },
    USERS: {
      GET: '/api/v1/admin/users',
      GET_ONE: (id: string) => `/api/v1/admin/users/${id}`,
      CREATE: '/api/v1/admin/users',
      UPDATE: (id: string): string => `/api/v1/admin/users/${id}`,
      DELETE: (id: string): string => `/api/v1/admin/users/${id}`,
    },
    PETS: {
      GET: '/api/v1/pets',
      GET_ONE: (id: string) => `/api/v1/pets/${id}`,
      CREATE: '/api/v1/pets',
      UPDATE: (id: string) => `/api/v1/pets/${id}`,
      DELETE: (id: string) => `/api/v1/pets/${id}`,
    },
  },
};
